# FIXME - Just testing that we can build for multi archs using docker in github actions
name: multi-arch-compile
run-name: Multi arch compile using docker and qemu
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
        with:
          platforms: "arm64"
      - run: bash make.sh
